# loki/loki-config.yml

auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      # On utilise un 'store' plus simple pour le développement local
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  # On définit explicitement les dossiers pour les index et les chunks
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks
  wal: 
    dir: /loki/wal 


# On configure le compactor pour qu'il ait son propre dossier
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

# On désactive la suppression des logs pour le développement
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
