# Configuration pour Presta La Express

[app]
name = "Presta La Express"
version = "1.0.0"
description = "Plateforme de mise en relation entre artisans et clients"
project_id = ""

[server]
host = "localhost"
port = 3000
environment = "development"

[database]
type = "mysql"
host = "localhost"
port = 3306
name = "presta_express"
charset = "utf8mb4"

[features]
auth_enabled = true
notifications_enabled = true
search_enabled = true
geolocation_enabled = true

[security]
cors_enabled = true
rate_limiting = true
max_requests_per_minute = 100

[logging]
level = "info"
format = "json"
output = "console"

[cache]
enabled = true
ttl = 3600
provider = "memory"