// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knbzqvnlhfoumgyiqvch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYnpxdm5saGZvdW1neWlxdmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODk2NTcsImV4cCI6MjA1ODc2NTY1N30.Xf-AO1MbBQCwftNFN01ovoJudRqgrrIFFmDUjYOBBlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});